In [9]:
# we are importing numpy lib as np
import numpy as np

In [10]:
# let's create a list with 10 elements
arr=[3,5,3,5,3,5,3,5,3,5]

In [12]:
# convert the list to a numpy array using np.array
np_arr=np.array(arr)
# print the numpy array
print(np_arr)

[3 5 3 5 3 5 3 5 3 5]


In [13]:
# check the type of the numpy array
print(type(np_arr))
# check the shape of the numpy array
print(np_arr.shape)
# check the size of the numpy array
print(np_arr.size)
# check the datatype of the numpy array
print(np_arr.dtype)
# check the number of dimensions of the numpy array
print(np_arr.ndim)

<class 'numpy.ndarray'>
(10,)
10
int32
1


In [ ]:
#let's create a 2D numpy array using np.array
arr2=[[1,2,3],[4,5,6],[7,8,9]]
# convert the list to a numpy array using np.array
np_arr2=np.array(arr2)
# print the numpy array
print(np_arr2)
# check the matrix of the numpy array
print(np_arr2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [17]:
# some features of numpy arrays
# Arange function is used to create an array with a range of numbers
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
# create a matrix of 4 rows and 5 columns of zeros using np.zeros
#1D array of zeros
arr1=np.zeros(3)
#Multidimensional array of zeros
arr=np.zeros((4,5))
print(arr1)
print(arr)


[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
#using linspace function to create an array with 12 elements between 1 and 5
arr=np.linspace(1,5,12)
print(arr)

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


In [28]:
# using identity function to create a 3x3 identity matrix
arr=np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
#using reshape function to change the shape of the array
arr=np.arange(1,11)
print(arr)
arr=arr.reshape(5,2)
print(arr)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)
