In [1]:
import numpy as np

In [2]:
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
#Iteration in 1-D array
for val in a:
    print(val)

1
2
3
4
5
6
7
8
9
10


In [14]:
#Iteration in 2-D array
b=np.array([[1,2,3],[4,5,6]])
for x in b[0:2]:
    for y in x[0:2]:
     print(y)

1
2
4
5


In [24]:
#Iteration in 3-D array
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in c[:1]:
    print(x)
    for y in x:
        print(y)
        for z in y:
            print(z)

[[1 2]
 [3 4]]
[1 2]
1
2
[3 4]
3
4


In [26]:
# Iteration with nditer
for x in np.nditer(c):
    print(x)

1
2
3
4
5
6
7
8


In [29]:
#Sorting in array
a=np.array([4,3,25,6,7,32,4,2,5,2])
a.sort()
print(a)

[ 2  2  3  4  4  5  6  7 25 32]


In [31]:
#Alphabetical sorting
a=np.array(['banana','apple','cherry','date'])
a.sort()
print(a)

['apple' 'banana' 'cherry' 'date']


In [32]:
#Boolean sorting
a=np.array([True,False,True,False])
a.sort()
print(a)

[False False  True  True]
