In [1]:
import numpy as np

In [5]:
#Create a 1D array and Get Shape
a=np.array([1,2,3,4,5,6,7,8,9])
print(a.shape)

(9,)


In [8]:
#Create a 2D array and Get Shape
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
# 2 rows and 4 columns
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [ ]:
#Let's reshape 2-D array 
print(b.reshape(4,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
#Let's reshape 3-D array
c=np.arange(1,13)
print(c)
#here we reshaped 1D array to 3D array
# 2 rows, 3 columns and 2 depth
print(c.reshape(2,3,2))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [22]:
#Flatten the array
d=c.reshape(-1)
print(d)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
