In [27]:
import numpy as np

In [28]:
#create a 1D array
arr=np.arange(1,10)
print("1D array: ",arr)

1D array:  [1 2 3 4 5 6 7 8 9]


In [29]:
#Slicing the array
#return 2,3,4,5
print(arr[1:5])


[2 3 4 5]


In [30]:
#Return from something till the end of the array
print(arr[0:])
# we can print from this type of slicing too
print(arr[:len(arr)])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [31]:
#Return 7,8 from negative slicing
print(arr[-3:-1])

[7 8]


In [32]:
#printing array with steps
print(arr[1:5])
print(arr[1:10:4])

[2 3 4 5]
[2 6]


In [33]:
# 2-D array for Slicing
arr=np.arange(1,11).reshape(2,5)
print("2D array: ",arr)

2D array:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [34]:
# pulling out single item
print(arr[0,0]," ",arr[1,0])

1   6


In [ ]:
#sliceing item from 2D array
#0:1,0:4 means 0th row and 0 to 4th column
print(arr[0:1,0:4])

[[1 2 3 4]]


In [43]:
#Slicing the array from both rows
#this will not change the array we are slicing from it
print(arr[0:2,0:3])

[[1 2 3]
 [6 7 8]]
