In [7]:
import numpy as np

In [8]:
#square root of each element
a=np.array([1,2,3,4,5,6])
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [9]:
#Absolute value of each element
a=np.arange(-5,5)
print(np.absolute(a))

[5 4 3 2 1 0 1 2 3 4]


In [10]:
#For the exponential of each element
np.exp(a)

array([6.73794700e-03, 1.83156389e-02, 4.97870684e-02, 1.35335283e-01,
       3.67879441e-01, 1.00000000e+00, 2.71828183e+00, 7.38905610e+00,
       2.00855369e+01, 5.45981500e+01])

In [13]:
#for the minimum and maximum of an array
b=np.arange(1,12)
print(np.min(b))
print(np.max(b))

1
11


In [15]:
#Sign of each element
np.sign(a)

array([-1, -1, -1, -1, -1,  0,  1,  1,  1,  1])

In [23]:
#Mean of all elements
print(np.mean(b))
#Standard deviation of all elements
print(np.std(b))


6.0
3.1622776601683795
